SELECT MAX(SALARY) FROM hr.employees;

SELECT (MAX(SALARY) - MIN(SALARY)) FROM hr.employees;

SELECT JOB_ID, AVG(SALARY) AS AVG_SALARY FROM hr.employees
GROUP BY JOB_ID
ORDER BY AVG_SALARY DESC;

SELECT SUM(SALARY) AS TOTAL_SALARIES FROM hr.employees;

SELECT ROUND(MAX(SALARY), 2) AS MAX,
ROUND(MIN(SALARY), 2) MIN,
ROUND(SUM(SALARY), 2) TOTAL,
ROUND(AVG(SALARY), 2) AVG
FROM hr.employees;

SELECT JOB_ID, COUNT(*) FROM hr.employees
WHERE JOB_ID = 'IT_PROG';

SELECT JOB_ID, SUM(SALARY) FROM hr.employees
GROUP BY JOB_ID;

SELECT JOB_ID, SUM(SALARY) FROM hr.employees
GROUP BY JOB_ID
HAVING JOB_ID = 'IT_PROG';

SELECT JOB_ID, SUM(SALARY) AS SALARY FROM hr.employees
GROUP BY JOB_ID
HAVING NOT JOB_ID = 'IT_PROG'
ORDER BY SALARY DESC;

SELECT DEPARTMENT_ID, (SALARY) AS SALARY, COUNT(*) AS NUM_FUNC FROM hr.employees
GROUP BY DEPARTMENT_ID
HAVING NUM_FUNC > 10;

SELECT * FROM hr.employees;
SET SQL_SAFE_UPDATES = 0;
UPDATE hr.employees 
SET PHONE_NUMBER = REPLACE (PHONE_NUMBER, '515', '777')
WHERE PHONE_NUMBER LIKE '515%';

SELECT * FROM hr.employees
WHERE LENGTH(FIRST_NAME) >= 8;

SELECT EMPLOYEE_ID, FIRST_NAME, YEAR(HIRE_DATE) FROM hr.employees;

SELECT EMPLOYEE_ID, FIRST_NAME, DAY(HIRE_DATE) FROM hr.employees;

SELECT EMPLOYEE_ID, FIRST_NAME, MONTH(HIRE_DATE) FROM hr.employees;

SELECT UCASE(CONCAT(FIRST_NAME, ' ', LAST_NAME)) AS FULL_NAME FROM hr.employees;

SELECT LAST_NAME, HIRE_DATE FROM hr.employees
WHERE HIRE_DATE LIKE '1987-07%';

SELECT FIRST_NAME, LAST_NAME, DATEDIFF(NOW(), HIRE_DATE) AS TIME_OF_WORK FROM hr.employees;